# Find CLAPACK
# CLAPACK_INCLUDE_DIRS
# CLAPACK_LIBRARIES
# CLAPACK_FOUND

if(CLAPACK_FIND_QUIETLY)
  set(_FIND_CBLAS_ARG_QUIET)
endif(CLAPACK_FIND_QUIETLY)
find_package(CBLAS ${_FIND_CBLAS_ARG_QUIET})

if(CBLAS_FOUND)
	find_path(CLAPACK_INCLUDE_DIRS clapack.h)
	set(CMAKE_FIND_LIBRARY_SUFFIXES .a .so .so.3)
	set(CLAPACK_NAMES ${CLAPACK_NAMES} lapack)
	find_library(CLAPACK_LIBRARY NAMES ${CLAPACK_NAMES})
endif(CBLAS_FOUND)
	
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CLAPACK DEFAULT_MSG CLAPACK_LIBRARY CLAPACK_INCLUDE_DIRS)

if(CLAPACK_FOUND)
  find_library(GFORTRAN_LIBRARY NAMES gfortran)

  set(CLAPACK_INCLUDE_DIRS ${CLAPACK_INCLUDE_DIRS} ${CBLAS_INCLUDE_DIRS})
  set(CLAPACK_LIBRARIES ${CLAPACK_LIBRARY} ${GFORTRAN_LIBRARY} ${CBLAS_LIBRARIES})
endif(CLAPACK_FOUND)

mark_as_advanced(CLAPACK_LIBRARY CLAPACK_INCLUDE_DIRS)

